
spring:
  # 数据库相关配置
  datasource:
  # url: jdbc:mysql://39.108.110.248:3306/mmall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/mmall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 1
    maxActive: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 180000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

# mybaties 配置
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.kayak.dubbo_common.pojo

# 通用mapper 配置 自动生成dao层代码
# mapper:
  # plugin: tk.mybatis.mapper.generator.MapperPlugin
  # Mapper: tk.mybatis.mapper.common.Mapper
  # not-empty: false
  # identity: MYSQL